package com.example.project

actual fun L.ExampleContent.Pages.Page1.body(): String = ""
actual fun L.ExampleContent.Pages.Page1.title(): String = ""
actual fun L.ExampleContent.Pages.Page2.body(): String = ""
actual fun L.ExampleContent.Pages.Page2.title(): String = ""
actual fun L.ExampleContent.Pages.Page3.Body.checkmarks(): List<String> = emptyList()
actual fun L.ExampleContent.Pages.Page3.title(): String = ""
actual fun L.General.ampersand1(): String = ""
actual fun L.General.ampersand2(): String = ""
actual fun L.General.ampersand3(): String = ""
actual fun L.General.Button.ok(): String = ""
actual fun L.General.Error.invalidField(): String = ""
actual fun L.General.Error.tryAgainLater(): String = ""
actual fun L.General.iDontKnow(): String = ""
actual fun L.General.no(): String = ""
actual fun L.General.withParams(value0: String, value1: String): String = ""
actual fun L.General.yes(): String = ""
actual fun L.Greetings.hello(): String = ""
actual fun L.Listofobjects.Categories.Samplecategory.Content.body(): String = ""
actual fun L.Listofobjects.Categories.Samplecategory.Content.title(): String = ""
actual fun L.Listofobjects.Categories.Samplecategory.detailedDescription(): String = ""
actual fun L.Unit.gas(): String = ""
actual fun L.Unit.Power.u3(): String = ""
actual fun L.Unit.Power.u6(): String = ""
actual fun L.Unit.Power.u9(): String = ""
