// Generated by KMM Resources
package com.example.project

class L {
  companion object {
    val exampleContent: ExampleContent = ExampleContent()
    val general: General = General()
    val greetings: Greetings = Greetings()
    val listofobjects: Listofobjects = Listofobjects()
    val unit: Unit = Unit()
  }
  data class ExampleContent(
    val pages: Pages = Pages()) {
    data class Pages(
      val page1: Page1 = Page1(),
      val page2: Page2 = Page2(),
      val page3: Page3 = Page3()) {
      class Page1
      class Page2
      data class Page3(
        val body: Body = Body()) {
        class Body
      }
    }
  }
  data class General(
    val button: Button = Button(),
    val error: Error = Error()) {
    class Button
    class Error
  }
  class Greetings
  data class Listofobjects(
    val categories: Categories = Categories()) {
    data class Categories(
      val samplecategory: Samplecategory = Samplecategory()) {
      data class Samplecategory(
        val content: List<Content> = listOf(Content(0), Content(1))
) {
        data class Content(val index: Int)
      }
    }
  }
  data class Unit(
    val power: Power = Power()) {
    class Power
  }
}


expect fun L.ExampleContent.Pages.Page1.body(): String
expect fun L.ExampleContent.Pages.Page1.title(): String
expect fun L.ExampleContent.Pages.Page2.body(): String
expect fun L.ExampleContent.Pages.Page2.title(): String
expect fun L.ExampleContent.Pages.Page3.Body.checkmarks(): List<String>
expect fun L.ExampleContent.Pages.Page3.title(): String
expect fun L.General.ampersand1(): String
expect fun L.General.ampersand2(): String
expect fun L.General.ampersand3(): String
expect fun L.General.Button.ok(): String
expect fun L.General.Error.invalidField(): String
expect fun L.General.Error.tryAgainLater(): String
expect fun L.General.iDontKnow(): String
expect fun L.General.no(): String
expect fun L.General.withParams(value0: String, value1: String): String
expect fun L.General.yes(): String
expect fun L.Greetings.hello(): String
expect fun L.Listofobjects.Categories.Samplecategory.Content.body(): String
expect fun L.Listofobjects.Categories.Samplecategory.Content.title(): String
expect fun L.Listofobjects.Categories.Samplecategory.detailedDescription(): String
expect fun L.Unit.gas(): String
expect fun L.Unit.Power.u3(): String
expect fun L.Unit.Power.u6(): String
expect fun L.Unit.Power.u9(): String
